# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ZDNrZrP6nEpqgZmzFJsz-ex0V2AFx7P
"""

import torch
print(f"Pytorch version:{torch.__version__}")
print(f"Device available:{torch.cuda.is_available()}")

fake_images=torch.randn(32,1,28,28)
print("Original fake shape:",fake_images.shape)
flattened_images=torch.flatten(fake_images,start_dim=1)
print('Flattened image shape',flattened_images.shape)
layer=torch.nn.Linear(in_features=784,out_features=128)
output=layer(flattened_images)
print("Output shape",output.shape)

import torch.nn as nn
import torch.optim as optim
X=torch.randn(32,784)
y=torch.randint(0,10,(32,))
network=nn.Sequential(nn.Linear(in_features=784,out_features=128),nn.ReLU(),
                      nn.Linear(in_features=128,out_features=64),nn.ReLU(),
                       nn.Linear(in_features=64,out_features=10))
final=network(X)
criterion=nn.CrossEntropyLoss()
optimizer=optim.Adam(network.parameters(),lr=0.01)
loss=criterion(final,y)
print("Initial loss:",loss.item())
optimizer.zero_grad()
loss.backward()
optimizer.step()
new=network(X)
new_loss=criterion(new,y)
print("New loss after learning-",new_loss.item())
print("Final Output Shape:",final.shape)

neuralnet=nn.Sequential(nn.Linear(in_features=784,out_features=128),nn.ReLU(),
                        nn.Linear(in_features=128,out_features=64),nn.ReLU(),
                        nn.Linear(in_features=64,out_features=10))
optimizer=optim.Adam(neuralnet.parameters(),lr=0.01)
print("___Start Training___")
for epoch in range(1,21):
   prediction=neuralnet(X)
   loss=criterion(prediction,y)
   optimizer.zero_grad()
   loss.backward()
   optimizer.step()
   if epoch%2==0:
    print(f"Epoch{epoch:02d} | Current Loss:{loss.item():.4f}")
print("Training complete")

import torchvision
import torchvision.transforms as transforms
imgtotensor=transforms.Compose([transforms.ToTensor()])
print("Downloading Dataset")
train_dataset=torchvision.datasets.MNIST(root='./data',train=True,download=True,transform=imgtotensor)
train_loader=torch.utils.data.DataLoader(dataset=train_dataset,batch_size=32,shuffle=True)
images,labels=next(iter(train_loader))
print("--Data Loaded Successfully--")
print("Images Batch Shape",images.shape)
print("Labels Batch Shape:",labels.shape)
print("First 5 correct answers in batch",labels[:5].tolist())

import torch.nn as nn
import torch.optim as optim
neural=nn.Sequential(nn.Linear(in_features=784,out_features=128),nn.ReLU(),
                     nn.Linear(in_features=128,out_features=64),
                     nn.ReLU(),
                     nn.Linear(in_features=64,out_features=10))
optimizer=optim.Adam(neural.parameters(),lr=0.001)
for epoch in range(0,2):
  running_loss=0.0
  for batch_idx,(images,labels) in enumerate(train_loader):
      flattened_images=torch.flatten(images,start_dim=1)
      out=neural(flattened_images)
      loss=criterion(out,labels)
      optimizer.zero_grad()
      loss.backward()
      optimizer.step()
      running_loss+=loss.item()
      if (batch_idx+1)%400==0:
          average_batch_loss=running_loss/400
          print(f"Epoch {epoch:02d} | Batch {batch_idx + 1:04d}/{len(train_loader)} | Loss: {average_batch_loss:.4f}")
          running_loss=0.0
print("Training complete")

import matplotlib.pyplot as plt
test_image,true_label=train_dataset[42]
flattened_test=test_image.view(1,-1)
with torch.no_grad():
  raw_outputs=neural(flattened_test)
predicted_digit=torch.argmax(raw_outputs,dim=1).item()
print("True Label",true_label)
print("Networks Prediction",predicted_digit)
if predicted_digit==true_label:
  print("correct execution")
else:
  print("false execution")

test_dataset=torchvision.datasets.MNIST(root='./data',train=False,transform=imgtotensor)
test_loader=torch.utils.data.DataLoader(dataset=test_dataset,batch_size=64,shuffle=False)
correct=0
total=0
with torch.no_grad():
  for batch_idx, (images,labels) in enumerate(test_loader):
    flattened_images=images.view(images.size(0),-1)
    outputs=neural(flattened_images)
    predictions=torch.argmax(outputs,dim=-1)
    total+=labels.size(0)
    correct+=(predictions==labels).sum().item()
accuracy=correct/total*100
print("Accuracy of the model",accuracy)

class DigitCNN(nn.Module):
  def __init__(self):
    super(DigitCNN,self).__init__()
    self.features=nn.Sequential(nn.Conv2d(in_channels=1,out_channels=16,kernel_size=3,padding=1),
                                nn.ReLU(),nn.MaxPool2d(kernel_size=2,stride=2),
                                nn.Conv2d(in_channels=16,out_channels=32,kernel_size=3,padding=1),
                                nn.ReLU(),
                                nn.MaxPool2d(kernel_size=2,stride=2))
    self.classifier=nn.Sequential(nn.Flatten(),
                                  nn.Linear(in_features=1568,out_features=64),
                                  nn.ReLU(),
                                  nn.Linear(in_features=64,out_features=10))
  def forward(self,x):
    x=self.features(x)
    x=self.classifier(x)
    return x
cnn_model=DigitCNN()
print(cnn_model)
optimizers=optim.Adam(cnn_model.parameters(),lr=0.001)

for epoch in range(1,3):
  for batch,(images,labels) in enumerate(train_loader):
    prediction=cnn_model(images)
    initial_loss=criterion(prediction,labels)
    optimizers.zero_grad()
    initial_loss.backward()
    optimizers.step()
    running_loss+=initial_loss.item()
    if (batch+1)%400==0:
          average_batch_loss=running_loss/400
          print(f"Epoch {epoch:02d} | Batch {batch + 1:04d}/{len(train_loader)} | Loss: {average_batch_loss:.4f}")
          running_loss=0.0
print("Training complete")

correct1=0
total1=0
with torch.no_grad():
  for images,labels in test_loader:
    outputs=cnn_model(images)
    predic=torch.argmax(outputs,dim=-1)
    total1+=labels.size(0)
    correct1+=(predic==labels).sum().item()
cmm_accuracy=correct1/total1*100
print("The accuracy of the cnn model is",cmm_accuracy)

torch.save(cnn_model.state_dict(),"digit_cnn.path")

